/** Usta ko‘p tanlov — keng qamrovli xizmatlar ro‘yxati (qidiruv + ro‘yxat UI). */
export const WORKER_TRADE_OPTIONS = [
  "Santex montaj va ta’mir",
  "Elektr montaj va ta’mir",
  "Konditsioner montaj va servis",
  "Mebel yig‘ish va muntazamlash",
  "Bo‘yoq, shpatlyovka, devor",
  "Pol: laminat, linoleum, parket",
  "Deraza va eshik o‘rnatish",
  "Tom, chovqa, gidroizolatsiya",
  "Kanalizatsiya va suv quvurlari",
  "Umumiy kvartira ta’miri",
  "Gipsokarton, peregorodkalar",
  "Plitka, fayans, mozaika",
  "Sug‘orish va avtopoliv",
  "Yog‘och ishlar, duradgorlik",
  "Qazish, transsha, fundament",
  "Beton, styajka, sex poydevor",
  "Shift ta’miri, osma shift",
  "Issiqlik: radiator, qozonxona",
  "Ventilyatsiya montaji",
  "Video kuzatuv, signalizatsiya",
  "Elektr panel, avtomatlar, UPS",
  "Generator ulash va servis",
  "Ichim suvi filtrlari",
  "Maishiy texnika ta’miri",
  "Pech, plita, duxovka ta’miri",
  "Qulf, eshik mexanizmi",
  "PVC deraza, ramka almashtirish",
  "Issiq pol (suv, elektr)",
  "Tashqi fasad, moyka, sidirma",
  "Landshaft, sun’iy chim, gulzor",
  "Hovuz, fontan, basseyn yordamchi",
  "Loggia, veranda, terrasa",
  "Panjara, gratkalik, zarbalar",
  "Olma uvaleta, unitaz almashtirish",
  "Suv nasoslari va stantsiya",
  "Chimney, dudboda montaj",
  "Metall konstruksiya, payandalar",
  "Shifer, krisha qoplamasi",
  "Devor yopish, sayding",
  "Pardalar, jaluzi o‘rnatish",
  "Karniz, vodostok, oluk",
  "Liftga oid emas — zinapoyalar ta’miri",
  "Garaj eshiklari, avtomatik",
  "Kichik yuk tashish (mashina bilan)",
  "Axlat va qurilish chiqindi chiqarish",
  "Kafel kesish, figurali plitka",
  "Akustik, shovqin izolyatsiyasi",
  "Antenna, router, tarmoq tortish",
  "Maxsus buyurtma (boshqa xizmat)",
] as const;

export type WorkerTradeId = (typeof WORKER_TRADE_OPTIONS)[number];
